version: '2'

services:
  cqhttp:
    container_name: cqhttp
    image: richardchien/cqhttp:latest
    restart: always
    environment:
      COOLQ_ACCOUNT: 2729117176  # change to own bot account
      CQHTTP_SERVE_DATA_FILES: "yes"
    ports:
      - "9090:9000"
      - "5700:5700"
    volumes:
      - ../coolq:/home/user/coolq
  sprout:
    container_name: sprout
    build:
      context: .
      dockerfile: Dockfile-sprout
    restart: always
    environment:
      SUPER_ACCOUNT: 172950203 # change to own super account
    ports:
      - "8888:8888"
    volumes:
      - ../../sprout:/data/sprout
    depends_on:
      - cqhttp